
import type { Metadata } from "next";
import {SessionProvider} from 'next-auth/react';
import { Inter } from "next/font/google";
import "./globals.css";
import Header from "@/components/shared/header/page";
import Footer from "@/components/shared/footer/page";
import AppWrapper from '@/context/index';

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
       
     <body>
  
    <AppWrapper >
     <Header/>
   
      {children}
    
     <Footer/>
     </AppWrapper>
   
     </body>
    
    
    </html>
  );
}
